//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.19 at 11:24:00 PM CST 
//


package com.mocircle.jwinlog.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for EventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="System" type="{http://schemas.microsoft.com/win/2004/08/events/event}SystemPropertiesType"/>
 *         &lt;choice>
 *           &lt;element name="EventData" type="{http://schemas.microsoft.com/win/2004/08/events/event}EventDataType" minOccurs="0"/>
 *           &lt;element name="UserData" type="{http://schemas.microsoft.com/win/2004/08/events/event}UserDataType" minOccurs="0"/>
 *           &lt;element name="DebugData" type="{http://schemas.microsoft.com/win/2004/08/events/event}DebugDataType" minOccurs="0"/>
 *           &lt;element name="BinaryEventData" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *           &lt;element name="ProcessingErrorData" type="{http://schemas.microsoft.com/win/2004/08/events/event}ProcessingErrorDataType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="RenderingInfo" type="{http://schemas.microsoft.com/win/2004/08/events/event}RenderingInfoType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "system",
    "eventData",
    "userData",
    "debugData",
    "binaryEventData",
    "processingErrorData",
    "renderingInfo",
    "any"
})
public class EventType {

    @XmlElement(name = "System", required = true)
    protected SystemPropertiesType system;
    @XmlElement(name = "EventData")
    protected EventDataType eventData;
    @XmlElement(name = "UserData")
    protected UserDataType userData;
    @XmlElement(name = "DebugData")
    protected DebugDataType debugData;
    @XmlElement(name = "BinaryEventData", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] binaryEventData;
    @XmlElement(name = "ProcessingErrorData")
    protected ProcessingErrorDataType processingErrorData;
    @XmlElement(name = "RenderingInfo")
    protected RenderingInfoType renderingInfo;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link SystemPropertiesType }
     *     
     */
    public SystemPropertiesType getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemPropertiesType }
     *     
     */
    public void setSystem(SystemPropertiesType value) {
        this.system = value;
    }

    /**
     * Gets the value of the eventData property.
     * 
     * @return
     *     possible object is
     *     {@link EventDataType }
     *     
     */
    public EventDataType getEventData() {
        return eventData;
    }

    /**
     * Sets the value of the eventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDataType }
     *     
     */
    public void setEventData(EventDataType value) {
        this.eventData = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * @return
     *     possible object is
     *     {@link UserDataType }
     *     
     */
    public UserDataType getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDataType }
     *     
     */
    public void setUserData(UserDataType value) {
        this.userData = value;
    }

    /**
     * Gets the value of the debugData property.
     * 
     * @return
     *     possible object is
     *     {@link DebugDataType }
     *     
     */
    public DebugDataType getDebugData() {
        return debugData;
    }

    /**
     * Sets the value of the debugData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebugDataType }
     *     
     */
    public void setDebugData(DebugDataType value) {
        this.debugData = value;
    }

    /**
     * Gets the value of the binaryEventData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getBinaryEventData() {
        return binaryEventData;
    }

    /**
     * Sets the value of the binaryEventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinaryEventData(byte[] value) {
        this.binaryEventData = value;
    }

    /**
     * Gets the value of the processingErrorData property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingErrorDataType }
     *     
     */
    public ProcessingErrorDataType getProcessingErrorData() {
        return processingErrorData;
    }

    /**
     * Sets the value of the processingErrorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingErrorDataType }
     *     
     */
    public void setProcessingErrorData(ProcessingErrorDataType value) {
        this.processingErrorData = value;
    }

    /**
     * Gets the value of the renderingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RenderingInfoType }
     *     
     */
    public RenderingInfoType getRenderingInfo() {
        return renderingInfo;
    }

    /**
     * Sets the value of the renderingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenderingInfoType }
     *     
     */
    public void setRenderingInfo(RenderingInfoType value) {
        this.renderingInfo = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
