//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.19 at 11:24:00 PM CST 
//


package com.mocircle.jwinlog.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mocircle.jwinlog.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Event_QNAME = new QName("http://schemas.microsoft.com/win/2004/08/events/event", "Event");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mocircle.jwinlog.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemPropertiesType }
     * 
     */
    public SystemPropertiesType createSystemPropertiesType() {
        return new SystemPropertiesType();
    }

    /**
     * Create an instance of {@link RenderingInfoType }
     * 
     */
    public RenderingInfoType createRenderingInfoType() {
        return new RenderingInfoType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link DebugDataType }
     * 
     */
    public DebugDataType createDebugDataType() {
        return new DebugDataType();
    }

    /**
     * Create an instance of {@link EventDataType }
     * 
     */
    public EventDataType createEventDataType() {
        return new EventDataType();
    }

    /**
     * Create an instance of {@link ProcessingErrorDataType }
     * 
     */
    public ProcessingErrorDataType createProcessingErrorDataType() {
        return new ProcessingErrorDataType();
    }

    /**
     * Create an instance of {@link UserDataType }
     * 
     */
    public UserDataType createUserDataType() {
        return new UserDataType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link ComplexDataType }
     * 
     */
    public ComplexDataType createComplexDataType() {
        return new ComplexDataType();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.Provider }
     * 
     */
    public SystemPropertiesType.Provider createSystemPropertiesTypeProvider() {
        return new SystemPropertiesType.Provider();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.EventID }
     * 
     */
    public SystemPropertiesType.EventID createSystemPropertiesTypeEventID() {
        return new SystemPropertiesType.EventID();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.TimeCreated }
     * 
     */
    public SystemPropertiesType.TimeCreated createSystemPropertiesTypeTimeCreated() {
        return new SystemPropertiesType.TimeCreated();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.EventRecordID }
     * 
     */
    public SystemPropertiesType.EventRecordID createSystemPropertiesTypeEventRecordID() {
        return new SystemPropertiesType.EventRecordID();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.Correlation }
     * 
     */
    public SystemPropertiesType.Correlation createSystemPropertiesTypeCorrelation() {
        return new SystemPropertiesType.Correlation();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.Execution }
     * 
     */
    public SystemPropertiesType.Execution createSystemPropertiesTypeExecution() {
        return new SystemPropertiesType.Execution();
    }

    /**
     * Create an instance of {@link SystemPropertiesType.Security }
     * 
     */
    public SystemPropertiesType.Security createSystemPropertiesTypeSecurity() {
        return new SystemPropertiesType.Security();
    }

    /**
     * Create an instance of {@link RenderingInfoType.Keywords }
     * 
     */
    public RenderingInfoType.Keywords createRenderingInfoTypeKeywords() {
        return new RenderingInfoType.Keywords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/win/2004/08/events/event", name = "Event")
    public JAXBElement<EventType> createEvent(EventType value) {
        return new JAXBElement<EventType>(_Event_QNAME, EventType.class, null, value);
    }

}
